name: generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: muqeetahmaad9
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%237b2ff7&color_dots=%230d0221,%233d1a63,%237b2ff7,%23be29ec,%23f72585
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2300fff2&color_dots=%230d0221,%233d1a63,%237b2ff7,%23be29ec,%23f72585

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
